require_relative './ultra_races/version.rb'
require_relative './ultra_races/cli.rb'
require_relative './ultra_races/scraper.rb'
require_relative './ultra_races/ultra.rb'
require 'open-uri'
require 'nokogiri'
require 'pry'
